### ISSUE TITLE
Issue with multiple Heroku dynos and in-memory session info

### ISSUE THREAD

**Issue by astoeckley** [cemerick/friend#146]
Hi Chas, thanks for your work on this library, we've been using it fine for quite a while. We finally upgraded to more than one dyno at Heroku, and everything kinda fell apart; the session information in friend stopped grabbing the email about half the time. I interacted with Heroku and they indicated that since requests can be routed around between dynos, then in-memory session information cannot be relied upon. I do not know if this affects Friend or not, and if it is the cause of what we've seen. The issue went away when we scaled back to a single dyno. In perusing the source, I see at least one instance of an atom in use, so that would suggest to me maybe there is a bit of stored state that needs to be there upon the return from a workflow provider like Google. If that's the case and there is no workaround, I'll look at installing some Heroku tools to always route requests back to the same dyno, which is not Heroku's best advice, but it is available if necessary.

**Comment by cemerick** [comment]
The core of friend and the simpler workflows (form login, HTTP Basic, etc) doesn't depend upon in-memory sessions; if you use a persistent ring session backend (storing sessions in e.g. redis, memcached, or a RDBMS), then these workflws and friend will work transparently.

The OpenId workflow definitely relies upon in-memory sessions, in part due to that atom, but also the underlying openid4java library maintains its own in-process caches and other state that can't be easily externalized AFAICT.

**Comment by astoeckley** [comment]
Thanks for the clarification. Yeah I'm using OpenID so I'm just getting Heroku to enable automatic return to the original dyno upon callback from the OpenID provider. No big deal, but wanted to check. Thanks Chas.
